name: hw1_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy==1.20.2
    - pandas==1.2.4
    - tqdm
    - jupyter
    - matplotlib
    - seaborn
    - jupyterthemes==0.20.0
    - imblearn==0.0
    - torch==2.0.0
    - xgboost==1.7.5
